### ISSUE TITLE
help formatting legend

### ISSUE THREAD

**Issue by kayneryan** [ds5010/vaccines#59]
Hi all-- 
Matt and I could use your help. We can't get the 'size of population' legend to look quite right. We tried formatting the output but haven't found a good solution. Any ideas? 

*Option 1* 
We make the bubbles bigger. 
Pro: just add three zeroes to the end of the number to get the population (i.e. 6,000 is really 6,000,000)
Cons: the legend looks weird with the giant bubbles and the overlap over the numbers
![11-30-2021](https://user-images.githubusercontent.com/88462495/156100713-9a78c3f8-f8d1-4f38-baba-6b3d33426181.png)

*Option 2*
We keep the bubbles the same size.
Pro: the whole thing looks nicer (we can reduce the size of the legend box)
Cons: now you have to add four zeroes to get the population (i.e. 600 is really 6,000,000)
![11-30-2021](https://user-images.githubusercontent.com/88462495/156101272-c5f311c9-3248-442e-b7d3-246c913e1581.png)

**Comment by PhilipMathieu** [comment]
I misunderstood the problem - disregard my last comment

**Comment by PhilipMathieu** [comment]
This might be the solution: https://matplotlib.org/stable/api/collections_api.html#:~:text=funcfunction%2C%20default%3A%20lambda%20x%3A%20x
