### ISSUE TITLE
Unittest error for animation piece

### ISSUE THREAD

**Issue by sophiacofone** [ds5010/vaccines#76]
Hi all, I attempted to write a unittest to make sure the image files are appropriately named for the animation gif. It seems like the unittest is "testing", but it is incorrectly failing. On my end, the error is saying that there are differing elements ('06-30-2021.png' and '10-31-2021.png') as well as additional elements. My issue is I am not understanding this error as I believe all the names of files are correct. Could someone help me out with this? My code is under branch [sophia_unitte_animation](https://github.com/ds5010/vaccines/tree/sophia_unitte_animation) and the file name is [test_animation.py](https://github.com/ds5010/vaccines/blob/sophia_unitte_animation/tests/test_animation.py). Thank you!

**Comment by Satyajeet2000** [comment]
So, the issue here seems to be that listdir does not return files in any sorted order. In fact it only returns so in an arbitrary order. 

- Firstly, you need to put a comma right after '11-30-2021.png' at line 14
- Next: at line 22, use this:  self.assertEqual(self.files, sorted(list))

**Comment by Satyajeet2000** [comment]
![gitproblem](https://user-images.githubusercontent.com/44119198/159726804-0ce1c3e1-1d81-4122-8132-f41e8f0b64b0.png)

**Comment by sophiacofone** [comment]
Thank you, that makes sense! We do want them in sorted order so this works great.

**Comment by sophiacofone** [comment]
Thank you, that makes sense! We do want them in sorted order so this works great.
