### ISSUE TITLE
County Comparison Graph

### ISSUE THREAD

**Issue by b-mohler** [ds5010/vaccines#80]
Hey all,

I've uploaded new code to create the graph comparing Kent County, RI and Tuscaloosa County, AL (it's in the src folder in the bridget_redoing_graph branch). Currently there are two separate legends (one for the vax bars and another for the death lines), and I haven't found a way to unify them into one legend without sacrificing one of the y axes, and it seemed more important to retain those. Additionally, the y axis representing the % vaxxed doesn't go all the way up to 100, since it was autogenerated from the data which taps out at an 80 something % vax rate, but we could look into changing this manually if we think the visual would be cleaner/clearer with an axis that went to 100. I'm also open changing minor things like the color scheme or title/label texts if we think there are ways to make these clearer or more aesthetically cohesive with the rest of the project. Opinions/solutions regarding any of these thin

![](https://user-images.githubusercontent.com/98131490/160014266-26f5c85b-4a6e-49db-b927-2ae00a720de0.png)

**Comment by PhilipMathieu** [comment]
Noice noice noice. I think we should be able to get the "handles" out of each legend and just combine them. Haven't tested yet but here's the idea:
```python
handles_1, _ = ax1.get_legend_handles_labels()
handles_2, _ = ax2.get_legend_handles_labels()
ax2.legend(handles = handles_1.append(handles_2), loc='upper right')
```
