### ISSUE TITLE
gif not showing on gh-pages

### ISSUE THREAD

**Issue by PhilipMathieu** [ds5010/vaccines#91]

**Comment by PhilipMathieu** [comment]
https://getbootstrap.com/docs/5.1/examples/#:~:text=Bootstrap%20components%2C%20RTL.-,Navbars,-Taking%20the%20default

**Comment by sophiacofone** [comment]
I am not going to link the pull request because I don't want this issue to be closed totally, but pull request #93 helps bring the GH pages up to speed (so then we can translate it into HTML from there).
