### ISSUE TITLE
Help with HTML sizing (font and boxes)

### ISSUE THREAD

**Issue by sophiacofone** [ds5010/vaccines#95]
Hello, I am new to html and I am having some trouble with some of the details. I want to change the font of some of the text but I am struggling to see exactly where I can do that. Sometimes it seems like "fs=#" allows me to change it, but for this text box I can't find it.
<img width="1251" alt="Screen Shot 2022-04-03 at 9 14 45 PM" src="https://user-images.githubusercontent.com/95585108/161458613-d9601047-83b0-40c7-a189-441c02dbf329.png">
I also don't know how to reduce the whitespace/box size here:
<img width="1354" alt="Screen Shot 2022-04-03 at 9 15 58 PM" src="https://user-images.githubusercontent.com/95585108/161458683-ffe1ef3a-99c2-4139-a5f9-b62d9b9cd542.png">
I would want the grey box to end in line with the gif, but again I am struggling to locate what to change in the code to do this. Any HTML pointers would be great! The code is located [here](https://github.com/ds5010/vaccines/blob/soph_html/docs/index.html). Thank you!

**Comment by MatthewjRay** [comment]
I am no HTML expert (limited experience), and I cannot guarantee I can figure it out, but I will look at your code and see if I can help out in any way.

**Comment by pbogden** [comment]
Don't try to do it with CSS directly. Instead, use something like this...

`<p class="fs-5">To assess`

In other words, you change font size for the entire paragraph using bootstrap-defined classes. Here the class is "fs-5". There are other sizes as well. Here's the relevant section in bootstrap docs.

https://getbootstrap.com/docs/5.1/utilities/text/#font-size

**Comment by sophiacofone** [comment]
@pbogden Thank you! I didn't realize you could just stick that anywhere and it would adjust the font size, but that definitely works! Do you have any thoughts or documentation on adjusting the "white space" of the boxes so that it lines up better? Should I be looking at the containers or is that something else? https://getbootstrap.com/docs/5.1/layout/containers/

**Comment by pbogden** [comment]
I'd be careful about the documentation.  I think you might be talking about this...

https://getbootstrap.com/docs/5.0/utilities/flex/#align-items

But I'm not sure.  Don't spend a lot of time on it, and ping me in piazza if I'm slow to respond here.

Remember, this is about giving you a fish, not teaching you to fish.  It was good that you asked me your question.  If you have another specific request about styling that involves changing the bootstrap itself, then please let me know and I'll help you out. Can you give me something more specific?

**Comment by MatthewjRay** [comment]
Hi Sophia. It sounds like professor Bogden answered your question, but I found this to be a helpful resource in adjusting typography. 

https://getbootstrap.com/docs/5.0/content/typography/

**Comment by sophiacofone** [comment]
Closed per resolution of issue in class.
