### ISSUE TITLE
Adding county comparison to the README

### ISSUE THREAD

**Issue by sophiacofone** [ds5010/vaccines#97]
Opening this issue as a reminder to add the county comparison information to the README. Is there any additional technical information we want to include on the README that is not on the website?

**Comment by sophiacofone** [comment]
I started updating the readme (my changes are in pull request #99). Things we still may want to update:
1. We have some "future considerations" that we might want to remove, because we did them (I removed 2 I was sure of but I am unsure on a couple of the others)
2. We also might want to revise the makefile section/add some info on how the user can modify the FIPS code comparison.

**Comment by PhilipMathieu** [comment]
Closed by #99
